# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_usergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='code_name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='code_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
