# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20170508_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='assign_to_staff',
            field=models.BooleanField(default=False),
        ),
    ]
