# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_editorlist_date'),
        ('home', '0002_remove_post_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
    ]
