# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='entry',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.Video'),
        ),
    ]
