# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20161013_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='icon',
            field=models.ImageField(blank=b'base.png', upload_to=b'label/'),
        ),
    ]
