# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
