# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20161110_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Label'),
        ),
    ]
