# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20161110_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaibaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('type', models.CharField(max_length=300, unique=True)),
            ],
        ),
    ]
