# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20170115_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saibasettings',
            name='value',
            field=models.FloatField(),
        ),
    ]
