# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20161002_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=b'icon/'),
        ),
    ]
