# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_state_ergreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='video',
            name='entry',
        ),
    ]
