# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_comment_votes'),
        ('gallery', '0009_auto_20161012_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ManyToManyField(blank=True, to='feedback.Comment'),
        ),
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(blank=True, to='feedback.Comment'),
        ),
    ]
