# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_auto_20161013_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
    ]
