# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0020_auto_20170506_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='trending_points',
            field=models.IntegerField(default=0),
        ),
    ]
