# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20170510_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='comments_locked',
            field=models.BooleanField(default=False),
        ),
    ]
