# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0002_auto_20160922_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('source', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=250)),
                ('hidden', models.BooleanField(default=False)),
                ('file', models.ImageField(blank=True, upload_to=b'')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
            ],
        ),
    ]
