# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_origin', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(max_length=250)),
                ('hidden', models.BooleanField(default=False)),
                ('file', models.ImageField(blank=True, upload_to=b'icon/')),
                ('file_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('trending_points', models.IntegerField(default=0)),
                ('comments_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('code_name', models.CharField(default=b'', max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_origin', models.CharField(blank=True, max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('trending_points', models.IntegerField(default=0)),
                ('comments_locked', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.State')),
            ],
        ),
    ]
