# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 01:36
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170604_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='video',
            name='media',
            field=embed_video.fields.EmbedVideoField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
