# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20161002_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=250),
        ),
    ]
