# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_state_ergreg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='ergreg',
        ),
    ]
