# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20161110_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='trending_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entry.Entry'),
        ),
    ]
