# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20170101_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_origin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date_origin',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
