# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20170102_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_origin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_origin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
