# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_auto_20170308_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=b'icon/'),
        ),
    ]
