# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_image_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, upload_to=b'icon/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_url',
            field=models.CharField(blank=True, default=b'', max_length=250),
        ),
    ]
