# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0023_auto_20170510_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
