# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0025_auto_20170524_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='code_name',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
