# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=250)),
                ('permissions', models.ManyToManyField(to='staff.UserPermission')),
            ],
        ),
    ]
