# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20161223_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
