# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_usergroup'),
        ('profile', '0008_profile_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permissions',
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='staff.UserGroup'),
        ),
    ]
