# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-04 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entry', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([('id', 'slug')]),
        ),
    ]
