# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-17 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20170604_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='entryredirect',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, unique=True),
        ),
    ]
