# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20160927_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='commentsLocked',
            new_name='comments_locked',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='imagesLocked',
            new_name='images_locked',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='videosLocked',
            new_name='videos_locked',
        ),
    ]
