# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20160927_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='content',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
