# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_auto_20160929_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, default=b'icon/indice.png', upload_to=b'icon/'),
        ),
    ]
