# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_editorlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='entry.Entry'),
        ),
    ]
