# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20161030_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'comentaries'},
        ),
    ]
