# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_tag'),
        ('entry', '0011_auto_20161103_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='home.Tag'),
        ),
    ]
