# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_auto_20161215_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'icon/'),
        ),
    ]
