# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_auto_20170102_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_origin',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
