# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_auto_20170115_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingentry',
            name='entry',
        ),
        migrations.DeleteModel(
            name='TrendingEntry',
        ),
    ]
