# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_auto_20170102_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
