# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_auto_20170115_2008'),
        ('entry', '0020_auto_20170102_2102'),
    ]

    operations = [
    ]
