# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_auto_20170118_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, error_messages={b'invalid': b'Lel'}, upload_to=b'icon/'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='content',
            field=models.TextField(max_length=2500),
        ),
    ]
