# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_auto_20170318_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, error_messages={b'invalid_choice': b'Lel'}, upload_to=b'icon/'),
        ),
    ]
