# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20170416_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, default=b'', max_length=250, unique=True),
        ),
    ]
