# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20161029_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='response_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.Reply'),
        ),
    ]
