# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('0', 'Indefinido'), ('1', '$1 fez um coment\xe1rio em $2.'), ('2', '$1 respondeu o coment\xe1rio de $2.'), ('3', '$1 criou uma nova entrada.'), ('4', '$1 enviou uma nova imagem.'), ('5', '$1 enviou um novo v\xeddeo.'), ('6', '$1 editou uma entrada.'), ('7', '$1 editou uma imagem.'), ('8', '$1 editou um v\xeddeo.')], default=b'0', max_length=1),
        ),
        migrations.AlterField(
            model_name='action',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
