# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_auto_20170518_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
