# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0027_auto_20170520_0148'),
        ('feedback', '0025_auto_20170520_1600'),
    ]

    operations = [
    ]
