# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default=b'', max_length=250),
        ),
    ]
