# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=b'home/images/assets/avatar_default.svg', upload_to=b'avatars/'),
        ),
    ]
