# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-17 00:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20170604_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=profile.models.generate_code, max_length=32)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2017, 6, 23, 21, 52, 11, 133380))),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='home/images/assets/avatar_default.svg', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='token',
            name='related_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
