# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20161004_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=b'icon/perfil.png', upload_to=b'icon/'),
        ),
    ]
