# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-18 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20170616_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='code',
            field=models.CharField(default=profile.models.generate_code, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 24, 22, 47, 33, 642844)),
        ),
    ]
