# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-18 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20170617_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration_date',
            field=models.DateTimeField(default=profile.models.generate_expiration_date),
        ),
    ]
