# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('profile', '0007_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.ManyToManyField(to='staff.UserPermission'),
        ),
    ]
