# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_auto_20170508_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=1500),
        ),
    ]
