# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0039_auto_20170519_2321'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BPostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2500)),
                ('description', models.CharField(blank=True, max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, default=b'', max_length=250, unique=True)),
            ],
            options={
                'verbose_name_plural': 'contents',
            },
        ),
        migrations.CreateModel(
            name='BPost',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('content', models.CharField(blank=True, max_length=2500)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='content.BPostCategory')),
            ],
            options={
                'verbose_name_plural': 'bposts',
            },
            bases=('content.content',),
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
    ]
