# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20160922_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'icon/'),
        ),
    ]
