# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-28 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20170527_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='content',
            field=models.TextField(blank=True, max_length=2500),
        ),
    ]
