# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 20:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0007_auto_20160930_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
