# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20161110_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendingentry',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
    ]
