# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 22:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_entry_date_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_origin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
