# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_auto_20170118_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='additional_references',
        ),
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
