# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0033_redirectentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RedirectEntry',
            new_name='EntryRedirect',
        ),
    ]
