# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0008_remove_state_ergreg'),
        ('entry', '0008_editorlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, max_length=2500)),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.Category')),
                ('entry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry')),
                ('image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
                ('video', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Video')),
            ],
        ),
    ]
