# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-17 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='icon',
            field=models.ImageField(blank=True, upload_to='label/'),
        ),
    ]
