# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20161012_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2500)),
                ('description', models.CharField(blank=True, max_length=2500)),
                ('color', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
