# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20161013_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'label/'),
        ),
    ]
