# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20161013_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
