# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_post_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Label'),
        ),
    ]
