# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20161017_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('label', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.Label')),
            ],
        ),
    ]
