# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20160922_1545'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entry.Entry'),
        ),
    ]
