# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20161002_0226'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0004_commentvote_imagevote_videovote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.Image')),
                ('parent_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.ImageComment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='EntryComment',
        ),
        migrations.RenameModel(
            old_name='CommentVote',
            new_name='EntryCommentVote',
        ),
    ]
