# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20161006_0127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryCommentVote',
            new_name='CommentVote',
        ),
    ]
