# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20161011_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentvote',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='imagevote',
            name='is_positive',
        ),
        migrations.RemoveField(
            model_name='videovote',
            name='is_positive',
        ),
        migrations.AddField(
            model_name='commentvote',
            name='direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagevote',
            name='direction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videovote',
            name='direction',
            field=models.IntegerField(default=0),
        ),
    ]
