# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20161013_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='date',
            new_name='update_date',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='type',
        ),
        migrations.AddField(
            model_name='vote',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
