# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0008_auto_20161012_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='target',
            field=models.ForeignKey(blank=True, default=b'', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
