# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20161013_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
