# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_vote_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='target',
            new_name='target_content_type',
        ),
        migrations.AddField(
            model_name='vote',
            name='target_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
