# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_reply_response_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_NSFW',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
