# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_auto_20161012_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='target_id',
            field=models.PositiveIntegerField(),
        ),
    ]
