# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20161012_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
