# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_auto_20161014_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_comment',
            new_name='comment',
        ),
    ]
