# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0012_remove_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, to='feedback.Vote'),
        ),
    ]
