# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_comment_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
