# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-05 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0015_auto_20170417_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('0', '$1 fez um coment\xe1rio em $2.'), ('1', '$1 respondeu o coment\xe1rio de $2.'), ('2', '$1 criou uma nova entrada.'), ('3', '$1 enviou uma nova imagem.'), ('4', '$1 enviou um novo v\xeddeo.'), ('5', '$1 editou uma entrada.'), ('6', '$1 editou uma imagem.'), ('7', '$1 editou um v\xeddeo.')], default=b're', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_staff_only', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
