# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_auto_20170506_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[(b'0', b'Unknown'), (b'1', b'New comment'), (b'2', b'New reply'), (b'3', b'New entry'), (b'4', b'New image'), (b'5', b'New video'), (b'6', b'Edit entry'), (b'7', b'Edit image'), (b'8', b'Edit video')], default=b'0', max_length=1),
        ),
    ]
