# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-09 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_auto_20170506_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
