# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
