# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_auto_20161013_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
