# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_trendingvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingvote',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
