# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0032_auto_20170513_1831'),
        ('feedback', '0022_auto_20170520_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingvote',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trending_votes', to='entry.Entry'),
            preserve_default=False,
        ),
    ]
