# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-19 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0023_auto_20170518_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
