# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20170510_1334'),
        ('feedback', '0023_trendingvote_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingvote',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trending_votes', to='gallery.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trendingvote',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trending_votes', to='gallery.Video'),
            preserve_default=False,
        ),
    ]
