# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_auto_20170520_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingvote',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='trendingvote',
            name='target_id',
        ),
        migrations.AlterField(
            model_name='trendingvote',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_votes', to='entry.Entry'),
        ),
        migrations.AlterField(
            model_name='trendingvote',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_votes', to='gallery.Image'),
        ),
        migrations.AlterField(
            model_name='trendingvote',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_votes', to='gallery.Video'),
        ),
    ]
