# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0024_auto_20161013_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='vote',
            name='target_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
