# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0026_auto_20161013_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target_content_type',
        ),
    ]
