# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0027_remove_comment_target_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target_id',
        ),
    ]
