# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0028_remove_comment_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='target_id',
        ),
    ]
