# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bpost',
            options={'verbose_name_plural': 'BPosts'},
        ),
        migrations.AlterModelOptions(
            name='bpostcategory',
            options={'verbose_name_plural': 'BPost categories'},
        ),
        migrations.AddField(
            model_name='content',
            name='comments_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'icon/'),
        ),
        migrations.AddField(
            model_name='content',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
