# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20160922_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='commentsLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='imagesLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='videosLocked',
            field=models.BooleanField(default=False),
        ),
    ]
