# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20161012_2042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0009_auto_20161012_2042'),
        ('entry', '0009_editorlist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorlist',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='editorlist',
            name='user',
        ),
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(to='feedback.Comment'),
        ),
        migrations.AddField(
            model_name='entry',
            name='editors',
            field=models.ManyToManyField(related_name='entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='images',
            field=models.ManyToManyField(to='gallery.Image'),
        ),
        migrations.AddField(
            model_name='entry',
            name='videos',
            field=models.ManyToManyField(to='gallery.Video'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EditorList',
        ),
    ]
