# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_auto_20161012_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(related_name='parent_entry', to='feedback.Comment'),
        ),
    ]
