# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_entry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='home.Tag'),
        ),
    ]
