# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20161012_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='entry', to='feedback.Comment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='editors',
            field=models.ManyToManyField(related_name='editorship_entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
