# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0014_auto_20161012_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='comments',
        ),
    ]
