# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20161223_1438'),
        ('entry', '0016_auto_20170115_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='editorship',
            field=models.ManyToManyField(blank=True, to='profile.Profile'),
        ),
    ]
