# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-15 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_auto_20170115_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorlist',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='editorlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='EditorList',
        ),
    ]
