# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0013_comment_votes'),
        ('entry', '0017_remove_entry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='entry', to='feedback.Comment'),
        ),
    ]
