# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='additional_references',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
