# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_auto_20170318_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, error_messages={b'invalid': 'Insira um valor v\xe1lido.', b'invalid_image': 'Envie uma imagem v\xe1lida. O arquivo que voc\xea enviou n\xe3o \xe9 uma imagem ou \xe9 uma imagem corrompida. '}, upload_to=b'icon/'),
        ),
    ]
