# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0027_auto_20170318_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='icon',
            field=models.ImageField(blank=True, upload_to=b'icon/'),
        ),
    ]
