# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-10 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_auto_20170508_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
