# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-03 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0034_auto_20170526_1341'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([('id', 'slug')]),
        ),
    ]
